### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MyBug18** [MyBug18/To-The-Infinity#4]
- [x] Add a constructor to Planet class.

- [x] Write a test code.

- [x] Make a simple UI and test job movement.

**Comment by MyBug18** [comment]
Job movement checked with Debug.Log
Tested:
* Activate unemployed pop with POP.ActivatePOP()
* Move POP to different POPWorkingPlace.
* Switching slot in the same POPWorkingPlace.

Features about Upkeeps are weakly tested, need more strict testing.
